## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

# This function is to create a special "vector" 
# containing a series of function to process a matrix 
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  # set/initialize the values of matrix and its inverse
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  # get the value of the matrix
  get <- function() x
  # set the inverse of matrix for future cache call
  setinverse <- function(inverse) inv <<- inverse
  # get the cached inverse, if any 
  getinverse <- function() inv
  # a list of function object in the environment
  list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## Write a short comment describing this function
# Process the "vector" generated by makeCacheMatrix()
# if inverse if cached, get it;
# if not, calculate it and cache it using the 
# function in the "vector"
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  # try to get the cached inverse
  inv <- x$getinverse()
  # if there is cached inverse
  if(!is.null(inv)){ 
    message("getting matrix inverse")
    return(inv)
  }
  # if no cached inverse;  
  # get the matrix for calculation
  data <- x$get()
  # calculate the inverse
  inv <- solve(data, ...)
  # cache the inverse
  x$setinverse(inv)
  #return inverse
  inv
}
